import React, { useContext } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import './Home.css';

const Home = () => {
  const { user } = useContext(AuthContext);

  if (user) {
    return <Navigate to="/dashboard" replace />;
  }

  // High quality sample data to show off on landing page
  const sampleItinerary = {
    destination: "Tokyo, Japan",
    weather: { temp: 18, condition: "Sunny", icon: "01d", forecast: "Clear blue skies and comfortable spring weather." },
    currency: { code: "JPY", symbol: "¥", rate: 156.4 },
    day: {
      morning: "Start at Senso-ji Temple in Asakusa, Tokyo's oldest Buddhist temple. Walk through the Kaminarimon gate and explore the Nakamise-dori street vendor food.",
      afternoon: "Dive into Akihabara Electric Town for anime shops, neon displays, and modern gadget arcades. Grab a quick snack at a themed cafe.",
      evening: "Head to Shibuya Crossing to witness the world's busiest pedestrian crossing. Ascend to Shibuya Sky for a breathtaking panoramic sunset view over the city.",
      foodRecommendation: "Indulge in hot, fresh Tonkotsu Ramen at Ichiran or a local Izakaya in Shinjuku's Omoide Yokocho alley.",
      estimatedCost: "$35"
    }
  };

  return (
    <div className="home-container animate-fade-in">
      {/* Hero Section */}
      <header className="hero-section">
        <div className="hero-content">
          <div className="hero-badge">✦ AI-Powered Travel Assistant</div>
          <h1 className="hero-title">
            Craft Your Next <span className="gradient-text">Adventure</span> in Seconds
          </h1>
          <p className="hero-subtitle">
            Input your destination, duration, budget, and interests. Our advanced AI builds context-aware, day-by-day travel schedules with real-time weather and currency data.
          </p>
          <div className="hero-actions">
            {user ? (
              <Link to="/dashboard" className="btn btn-primary">
                Go to Dashboard <span>➔</span>
              </Link>
            ) : (
              <>
                <Link to="/signup" className="btn btn-primary">
                  Start Planning Free
                </Link>
                <Link to="/login" className="btn btn-secondary">
                  Sign In
                </Link>
              </>
            )}
          </div>
        </div>
        
        {/* Hero Decorative Glows */}
        <div className="hero-glow-1"></div>
        <div className="hero-glow-2"></div>
      </header>

      {/* Product Steps Section */}
      <section className="steps-section">
        <h2 className="section-title">How It Works</h2>
        <p className="section-subtitle">Plan a custom trip in three simple steps</p>
        
        <div className="steps-grid">
          <div className="step-card glass">
            <div className="step-number">1</div>
            <h3>Enter Preferences</h3>
            <p>Tell us your destination, trip length, budget level, and choose from multiple interest filters.</p>
          </div>
          
          <div className="step-card glass">
            <div className="step-number">2</div>
            <h3>Real-Time Check</h3>
            <p>We retrieve local weather forecasts and foreign exchange rates automatically for context.</p>
          </div>
          
          <div className="step-card glass">
            <div className="step-number">3</div>
            <h3>Get Itinerary</h3>
            <p>Receive your personalized plan containing activities, food suggestions, price quotes, and accommodation tips.</p>
          </div>
        </div>
      </section>

      {/* Interactive Preview Section */}
      <section className="preview-section">
        <div className="preview-layout">
          <div className="preview-info">
            <h2 className="section-title">Preview a Trip</h2>
            <p className="preview-text">
              Here is a glimpse of the rich day-by-day travel planners generated by TripCraft AI. Cards include visual timelines, weather guidelines, and budget conversions dynamically.
            </p>
            <div className="preview-features">
              <div className="feature-item">
                <span className="feature-icon">🌦️</span>
                <div>
                  <h4>Weather Integration</h4>
                  <p>Activities automatically shift to accommodate local forecasts.</p>
                </div>
              </div>
              <div className="feature-item">
                <span className="feature-icon">💱</span>
                <div>
                  <h4>Currency Calculation</h4>
                  <p>All costs are translated automatically into local currency rates.</p>
                </div>
              </div>
            </div>
          </div>

          {/* Sample Card Mockup */}
          <div className="preview-mockup glass">
            <div className="mockup-header">
              <div className="mockup-dest-info">
                <h3>{sampleItinerary.destination}</h3>
                <span className="badge-demo">Sample Generated Plan</span>
              </div>
              
              {/* Weather Demo */}
              <div className="weather-demo-badge">
                <span className="weather-icon-symbol">☀️</span>
                <div>
                  <span className="weather-temp-val">{sampleItinerary.weather.temp}°C</span>
                  <span className="weather-cond-desc">{sampleItinerary.weather.condition}</span>
                </div>
              </div>
            </div>

            <div className="mockup-body">
              <div className="mockup-timeline-item">
                <div className="timeline-dot morning"></div>
                <div className="timeline-content">
                  <h4>Morning Plan</h4>
                  <p>{sampleItinerary.day.morning}</p>
                </div>
              </div>

              <div className="mockup-timeline-item">
                <div className="timeline-dot afternoon"></div>
                <div className="timeline-content">
                  <h4>Afternoon Plan</h4>
                  <p>{sampleItinerary.day.afternoon}</p>
                </div>
              </div>

              <div className="mockup-timeline-item">
                <div className="timeline-dot evening"></div>
                <div className="timeline-content">
                  <h4>Evening Plan</h4>
                  <p>{sampleItinerary.day.evening}</p>
                </div>
              </div>

              <div className="mockup-extra-box">
                <div className="extra-item">
                  <span className="extra-label">🍜 Culinary Pick</span>
                  <p className="extra-val">{sampleItinerary.day.foodRecommendation}</p>
                </div>
                <div className="extra-item-row">
                  <div>
                    <span className="extra-label">💵 Est. Activities Cost</span>
                    <p className="extra-val">{sampleItinerary.day.estimatedCost} / ¥{(parseFloat(sampleItinerary.day.estimatedCost.replace('$', '')) * sampleItinerary.currency.rate).toFixed(0)} JPY</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
